language: java
jdk:
- oraclejdk8
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh ./scripts/deploy-jars.sh
  on:
    tags: true

after_success:
  - ./gradlew cobertura 
  - bash <(curl -s https://codecov.io/bash)
